//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookDepoSystem.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class T {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal T() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookDepoSystem.Common.T", typeof(T).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изглежда, че нямате права за достъп до страницата.
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъпът отказан.
        /// </summary>
        public static string AccessDeniedTitle {
            get {
                return ResourceManager.GetString("AccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възрастовият диапазон е задължително поле.
        /// </summary>
        public static string AgeRangeIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AgeRangeIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторът е задължително поле.
        /// </summary>
        public static string AuthorIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AuthorIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад към началната страница.
        /// </summary>
        public static string BackToIndex {
            get {
                return ResourceManager.GetString("BackToIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възрастов диапазон.
        /// </summary>
        public static string BookAgeRangeText {
            get {
                return ResourceManager.GetString("BookAgeRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string BookAuthorText {
            get {
                return ResourceManager.GetString("BookAuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корица.
        /// </summary>
        public static string BookCoverImageText {
            get {
                return ResourceManager.GetString("BookCoverImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид корица.
        /// </summary>
        public static string BookCoverTypeText {
            get {
                return ResourceManager.GetString("BookCoverTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настояща корица.
        /// </summary>
        public static string BookCurrentCoverImageText {
            get {
                return ResourceManager.GetString("BookCurrentCoverImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        public static string BookGenreText {
            get {
                return ResourceManager.GetString("BookGenreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфо.
        /// </summary>
        public static string BookInformationText {
            get {
                return ResourceManager.GetString("BookInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string BookISBNText {
            get {
                return ResourceManager.GetString("BookISBNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Място.
        /// </summary>
        public static string BookLocationText {
            get {
                return ResourceManager.GetString("BookLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление на книги.
        /// </summary>
        public static string BookManagementNavItem {
            get {
                return ResourceManager.GetString("BookManagementNavItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова корица.
        /// </summary>
        public static string BookNewCoverImageText {
            get {
                return ResourceManager.GetString("BookNewCoverImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой страници.
        /// </summary>
        public static string BookPagesText {
            get {
                return ResourceManager.GetString("BookPagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на публикуване.
        /// </summary>
        public static string BookPublishedDateText {
            get {
                return ResourceManager.GetString("BookPublishedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string BookQuantityAvailableText {
            get {
                return ResourceManager.GetString("BookQuantityAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        public static string BookSKUText {
            get {
                return ResourceManager.GetString("BookSKUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книжен инвентар.
        /// </summary>
        public static string BookTableTitle {
            get {
                return ResourceManager.GetString("BookTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавието на книгата е задължително поле.
        /// </summary>
        public static string BookTitleIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("BookTitleIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие.
        /// </summary>
        public static string BookTitleText {
            get {
                return ResourceManager.GetString("BookTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настоящата парола е невярна.
        /// </summary>
        public static string ChangePasswordErrorMessage {
            get {
                return ResourceManager.GetString("ChangePasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е променена успешно.
        /// </summary>
        public static string ChangePasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете новата парола.
        /// </summary>
        public static string ConfirmNewPasswordPlaceholderText {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждаване на парола.
        /// </summary>
        public static string ConfirmPasswordPlaceholderText {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видът на корицата е задължително поле.
        /// </summary>
        public static string CoverTypeIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CoverTypeIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова книга.
        /// </summary>
        public static string CreateBookTitle {
            get {
                return ResourceManager.GetString("CreateBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай.
        /// </summary>
        public static string CreateButtonText {
            get {
                return ResourceManager.GetString("CreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов наемател.
        /// </summary>
        public static string CreateRenterTitle {
            get {
                return ResourceManager.GetString("CreateRenterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов наем.
        /// </summary>
        public static string CreateRentTitle {
            get {
                return ResourceManager.GetString("CreateRentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница.
        /// </summary>
        public static string CurrentPageText {
            get {
                return ResourceManager.GetString("CurrentPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настояща парола.
        /// </summary>
        public static string CurrentPasswordPlaceholderText {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на книга.
        /// </summary>
        public static string DeleteBookTitle {
            get {
                return ResourceManager.GetString("DeleteBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли на книга.
        /// </summary>
        public static string DetailsBookTitle {
            get {
                return ResourceManager.GetString("DetailsBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайната дата не е валидна.
        /// </summary>
        public static string DueDateIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("DueDateIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайната дата трябва да е по-голяма от началната дата.
        /// </summary>
        public static string DueDateMustBeGreaterThanRentDate {
            get {
                return ResourceManager.GetString("DueDateMustBeGreaterThanRentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайна дата.
        /// </summary>
        public static string DueDateText {
            get {
                return ResourceManager.GetString("DueDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна на книга.
        /// </summary>
        public static string EditBookTitle {
            get {
                return ResourceManager.GetString("EditBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна на наемател.
        /// </summary>
        public static string EditRenterTitle {
            get {
                return ResourceManager.GetString("EditRenterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът е в невалиден формат.
        /// </summary>
        public static string EmailIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("EmailIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът е задължително поле.
        /// </summary>
        public static string EmailIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл адрес.
        /// </summary>
        public static string EmailPlaceholderText {
            get {
                return ResourceManager.GetString("EmailPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола?.
        /// </summary>
        public static string ForgotPasswordLinkText {
            get {
                return ResourceManager.GetString("ForgotPasswordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашата заявка беше успешна. Моля проверете имейл адреса си за линк за промяна на парола..
        /// </summary>
        public static string ForgotPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанрът е задължително поле.
        /// </summary>
        public static string GenreIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("GenreIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информацията е задължително поле.
        /// </summary>
        public static string InformationIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("InformationIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът или паролата не съвпадат.
        /// </summary>
        public static string InvalidLoginErrorMessage {
            get {
                return ResourceManager.GetString("InvalidLoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спомних си паролата.
        /// </summary>
        public static string IRememberedMyPasswordLinkText {
            get {
                return ResourceManager.GetString("IRememberedMyPasswordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN е задължително поле.
        /// </summary>
        public static string IsbnIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("IsbnIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мястото на книгата е задължително поле.
        /// </summary>
        public static string LocationIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("LocationIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string LogoutButtonText {
            get {
                return ResourceManager.GetString("LogoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да излезете от Вашия профил?.
        /// </summary>
        public static string LogoutModalMessage {
            get {
                return ResourceManager.GetString("LogoutModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход от системата.
        /// </summary>
        public static string LogoutModalTitle {
            get {
                return ResourceManager.GetString("LogoutModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова парола.
        /// </summary>
        public static string NewPasswordPlaceholderText {
            get {
                return ResourceManager.GetString("NewPasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следваща.
        /// </summary>
        public static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции.
        /// </summary>
        public static string OperationsText {
            get {
                return ResourceManager.GetString("OperationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Броят на страниците е задължително поле.
        /// </summary>
        public static string PagesIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PagesIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдената парола не съвпада.
        /// </summary>
        public static string PasswordIsDifferentThanConfirmedErrorMessage {
            get {
                return ResourceManager.GetString("PasswordIsDifferentThanConfirmedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е задължително поле.
        /// </summary>
        public static string PasswordIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string PasswordPlaceholderText {
            get {
                return ResourceManager.GetString("PasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да съдържа малка буква.
        /// </summary>
        public static string PasswordRequiresLowerErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresLowerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да съдържа символ.
        /// </summary>
        public static string PasswordRequiresNonAlphanumericErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да съдържа голяма буква.
        /// </summary>
        public static string PasswordRequiresUpperErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresUpperErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да е поне 6 символа.
        /// </summary>
        public static string PasswordTooShortErrorMessage {
            get {
                return ResourceManager.GetString("PasswordTooShortErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предишна.
        /// </summary>
        public static string PreviousPageText {
            get {
                return ResourceManager.GetString("PreviousPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датата на публикуване е невалидна.
        /// </summary>
        public static string PublishedDateIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PublishedDateIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количеството трябва да е положително число.
        /// </summary>
        public static string QuantityAvailableIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("QuantityAvailableIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме.
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга.
        /// </summary>
        public static string RentBookText {
            get {
                return ResourceManager.GetString("RentBookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датата на наемане е невалидна.
        /// </summary>
        public static string RentDateIsIncorrectErrorMessage {
            get {
                return ResourceManager.GetString("RentDateIsIncorrectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Началната дата не е валидна.
        /// </summary>
        public static string RentDateIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("RentDateIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начална дата.
        /// </summary>
        public static string RentDateText {
            get {
                return ResourceManager.GetString("RentDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът на наемателят е задължително поле.
        /// </summary>
        public static string RenterEmailIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("RenterEmailIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл.
        /// </summary>
        public static string RenterEmailText {
            get {
                return ResourceManager.GetString("RenterEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наематели.
        /// </summary>
        public static string RenterManagementNavItem {
            get {
                return ResourceManager.GetString("RenterManagementNavItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името на наемателят е задължително поле.
        /// </summary>
        public static string RenterNameIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("RenterNameIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string RenterNameText {
            get {
                return ResourceManager.GetString("RenterNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонният номер на наемателят е задължително поле.
        /// </summary>
        public static string RenterPhoneNumberIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("RenterPhoneNumberIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер.
        /// </summary>
        public static string RenterPhoneNumberText {
            get {
                return ResourceManager.GetString("RenterPhoneNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наематели.
        /// </summary>
        public static string RenterTableTitle {
            get {
                return ResourceManager.GetString("RenterTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наемател.
        /// </summary>
        public static string RentRenterText {
            get {
                return ResourceManager.GetString("RentRenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string RentStatusText {
            get {
                return ResourceManager.GetString("RentStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наеми.
        /// </summary>
        public static string RentTableTitle {
            get {
                return ResourceManager.GetString("RentTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смени паролата.
        /// </summary>
        public static string ResetPasswordButtonText {
            get {
                return ResourceManager.GetString("ResetPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на парола.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датата на връщане не е валидна.
        /// </summary>
        public static string ReturnDateIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("ReturnDateIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датата на връщане трябва да е по-голяма от началната дата.
        /// </summary>
        public static string ReturnDateMustBeGreaterThanRentDate {
            get {
                return ResourceManager.GetString("ReturnDateMustBeGreaterThanRentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на връщане.
        /// </summary>
        public static string ReturnDateText {
            get {
                return ResourceManager.GetString("ReturnDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Върни наем.
        /// </summary>
        public static string ReturnRentTitle {
            get {
                return ResourceManager.GetString("ReturnRentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраната книга не е налична.
        /// </summary>
        public static string SelectedBookNotAvailable {
            get {
                return ResourceManager.GetString("SelectedBookNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати заявка за промяна на парола.
        /// </summary>
        public static string SendResetRequestButtonText {
            get {
                return ResourceManager.GetString("SendResetRequestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU е задължително поле.
        /// </summary>
        public static string SkuIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("SkuIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статусът е задължително поле.
        /// </summary>
        public static string StatusIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("StatusIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавието е задължително поле.
        /// </summary>
        public static string TitleIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TitleIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът Ви е временно заключен.
        /// </summary>
        public static string UserLockedOutErrorMessage {
            get {
                return ResourceManager.GetString("UserLockedOutErrorMessage", resourceCulture);
            }
        }
    }
}
